### ISSUE TITLE
Make text readable in dark UI of Chrome Inspector

### ISSUE THREAD

**Issue by simsketch** [stml/welcomejs#10]
![image](https://cloud.githubusercontent.com/assets/3129129/20494483/2624a71c-afeb-11e6-80de-d1071f47afc3.png)

**Comment by hugovk** [comment]
This was updated in https://github.com/stml/welcomejs/pull/9 but the demo page is on another branch and is using an older copy of welcome.js. Compare:

https://github.com/stml/welcomejs/blob/master/welcome.js
https://github.com/stml/welcomejs/blob/gh-pages/javascripts/welcome.js 

Here's a PR to update it: https://github.com/stml/welcomejs/pull/12

It'd be also good to include a version number in the .js file (and possibly also the .min.js) so it's clear which is which.

**Comment by stml** [comment]
Thanks all, this has been merged.
