### ISSUE TITLE
Add to cdnjs

### ISSUE THREAD

**Issue by hugovk** [stml/welcomejs#6]
At the time of writing, welcome.js has 127 GitHub stars and is eligible for [cdnjs](https://github.com/cdnjs/cdnjs). ⭐️ 

This library will need a package.json file: https://github.com/cdnjs/cdnjs#create-or-update-packagejson

**Comment by stml** [comment]
Yes! Have made a pull request with what I think is the right details: https://github.com/cdnjs/cdnjs/pull/10157 (from https://github.com/stml/cdnjs/).

It says tests have failed. I don't understand that, so.

**Comment by hugovk** [comment]
The "failed" test is:

```
==========ERROR==========

Please do not send pull request from master branch!\nYou should create a new branch with meaningful name for pull request!

==========ERROR==========
```

And so it is:

> 	stml  wants to merge 4 commits into cdnjs:master from stml:master
https://github.com/cdnjs/cdnjs/pull/10157

To fix, go to https://github.com/stml/cdnjs/, click the "master" dropdown above the file list:

![image](https://cloud.githubusercontent.com/assets/1324225/21590627/4567aa2a-d106-11e6-8ee9-6c3610711cb0.png)

Then enter a new branch name like "welcome.js" and make the PR from that branch and close the old one.

**Comment by PeterDaveHello** [comment]
Happy New Year 🎉   CDNJS maintainer here 😄 , plesae also give the released version a valid git tag in this repo, so that we can apply auto-update config on it, that's how do we recognize a version, thanks! 👍
