### ISSUE TITLE
Misleading intent

### ISSUE THREAD

**Issue by nemoDreamer** [stml/welcomejs#7]
It's a shame that in an effort to promote the wonderful "open source autodidact" nature of the dev console, your article misses the point Facebook is trying to make, especially regarding their demographic...

They’re not saying **“STOP! You have no right being here!”**, they’re saying “STOP! If somebody told you to paste something in here, you might not know what it’ll do! Here's a way it could possibly go very nastily for you who might not be a developer or interested in learning about development!"

**Comment by nemoDreamer** [comment]
And yes, your message is of course way more welcoming, I'm not bashing this project, but for someone who's opened the dev console on Facebook with the intent of pasting something that'll make their experience "trust me -- way more awesome!", a big "Welcome!" header is all they need to just TL;DR on the rest and go ahead and paste.

**Comment by stml** [comment]
Hi, thanks for your message.

(a) The blog post says, explicitly: "I understand why Facebook has done this: their users are subjected to many different and many nasty attempts to hack them, some of which include persuading them to do stuff in the console they shouldn’t do, like Self-XSS attacks."

(b) Facebook does not say "STOP! If somebody told you to paste something in here, you might not know what it’ll do! Here's a way it could possibly go very nastily for you who might not be a developer or interested in learning about development!". They say "This is a browser feature intended for developers. If someone told you to copy-paste something here to enable a Facebook feature or "hack" someone's account, it is a scam and will give them access to your Facebook account." There's nothing there about _learning_ about development, which is the point of the script.

(c) I don't expect Facebook to use this script, obviously.
